github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/boyfriendtv-downloader",
  "https://serp.co/products/boyfriendtv-downloader/reviews/",
  "https://extensions.serp.co/boyfriendtv-downloader",
  "https://browserextensions.io/boyfriendtv-downloader"
]
